FROM joomla:6.1-php8.3-apache

ARG JOOMLA_VERSION=6.1.1
ARG JOOMLA_PACKAGE_URL=https://github.com/joomla/joomla-cms/releases/download/${JOOMLA_VERSION}/Joomla_${JOOMLA_VERSION}-Stable-Full_Package.zip

RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

RUN rm -rf /usr/src/joomla/* /var/www/html/* \
    && curl -fsSL "$JOOMLA_PACKAGE_URL" -o /tmp/joomla.zip \
    && unzip -q /tmp/joomla.zip -d /usr/src/joomla \
    && rm /tmp/joomla.zip

RUN echo "PassEnv J2COMMERCE_TEST_MODE" >> /etc/apache2/apache2.conf

COPY extension.zip /tmp/extension.zip
COPY j2commerce6.zip /tmp/j2commerce6.zip

COPY scripts/docker-entrypoint-j6.sh /usr/local/bin/custom-entrypoint.sh
RUN chmod +x /usr/local/bin/custom-entrypoint.sh

ENV EXTENSION_NAME="J2Commerce Privacy Plugin (J6)"
ENV J2COMMERCE_STACK=j6

ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
CMD ["apache2-foreground"]
